import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import { Sparkles, Clock, Users, Zap, Trophy, Play } from "lucide-react";
import { useState } from "react";

interface Quest {
  id: string;
  title: string;
  description: string;
  aiGenerated: boolean;
  location: string;
  difficulty: "Easy" | "Medium" | "Hard";
  duration: string;
  maxPlayers: number;
  currentPlayers: number;
  rewards: {
    xp: number;
    badges?: string[];
    items?: string[];
  };
  progress?: number;
  status: "available" | "active" | "completed";
  questType: "solo" | "multiplayer" | "guild";
}

const activeQuests: Quest[] = [
  {
    id: "library-1",
    title: "The Ancient Algorithm Mystery",
    description: "Decode the secrets hidden in the library's AI-generated historical database. Work with your team to unlock knowledge artifacts scattered throughout the archives.",
    aiGenerated: true,
    location: "Knowledge Nexus",
    difficulty: "Medium",
    duration: "25 min",
    maxPlayers: 4,
    currentPlayers: 3,
    rewards: {
      xp: 150,
      badges: ["Knowledge Seeker"],
      items: ["Ancient Scroll NFT"]
    },
    progress: 65,
    status: "active",
    questType: "multiplayer"
  },
  {
    id: "cafeteria-1", 
    title: "Social Fusion Challenge",
    description: "Connect with 5 new students and complete collaborative mini-games. Each interaction unlocks new conversation paths generated by AI based on shared interests.",
    aiGenerated: true,
    location: "Social Hub Central",
    difficulty: "Easy",
    duration: "15 min",
    maxPlayers: 10,
    currentPlayers: 7,
    rewards: {
      xp: 100,
      badges: ["Social Butterfly"],
      items: ["Friend Token"]
    },
    status: "available",
    questType: "multiplayer"
  }
];

const availableQuests: Quest[] = [
  {
    id: "lab-1",
    title: "AR Innovation Lab",
    description: "Design and test a new AR experience using the campus Innovation Chamber. Your creation will be judged by AI and faculty mentors.",
    aiGenerated: false,
    location: "Innovation Chamber", 
    difficulty: "Hard",
    duration: "45 min",
    maxPlayers: 1,
    currentPlayers: 0,
    rewards: {
      xp: 300,
      badges: ["Innovation Master", "AR Pioneer"],
      items: ["Holographic Blueprint"]
    },
    status: "available",
    questType: "solo"
  },
  {
    id: "guild-1",
    title: "Dragon Raid: Campus Edition",
    description: "Team up with your guild to defeat the legendary Campus Dragon in this epic AR battle spanning multiple locations. Requires guild coordination and strategy.",
    aiGenerated: true,
    location: "Multiple Locations",
    difficulty: "Hard", 
    duration: "60 min",
    maxPlayers: 20,
    currentPlayers: 12,
    rewards: {
      xp: 500,
      badges: ["Dragon Slayer", "Guild Champion"],
      items: ["Dragon Scale Artifact", "Victory Crown NFT"]
    },
    status: "available",
    questType: "guild"
  }
];

const QuestSystem = () => {
  const [selectedTab, setSelectedTab] = useState<"active" | "available">("active");

  const getDifficultyColor = (difficulty: Quest['difficulty']) => {
    switch (difficulty) {
      case 'Easy': return 'bg-success text-background';
      case 'Medium': return 'bg-warning text-background'; 
      case 'Hard': return 'bg-destructive text-destructive-foreground';
    }
  };

  const getQuestTypeColor = (type: Quest['questType']) => {
    switch (type) {
      case 'solo': return 'bg-primary/20 text-primary';
      case 'multiplayer': return 'bg-secondary/20 text-secondary';
      case 'guild': return 'bg-accent/20 text-accent';
    }
  };

  const questsToShow = selectedTab === "active" ? activeQuests : availableQuests;

  return (
    <div className="space-y-6">
      {/* Header */}
      <Card className="bg-gradient-card border-primary/20 shadow-card">
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Sparkles className="h-5 w-5 text-primary animate-pulse-glow" />
            AI-Powered Quest System
          </CardTitle>
          <CardDescription>
            Dynamic adventures generated by advanced AI, tailored to your interests and campus events
          </CardDescription>
        </CardHeader>
      </Card>

      {/* Tab Navigation */}
      <div className="flex space-x-1 bg-muted/50 p-1 rounded-lg">
        <Button
          variant={selectedTab === "active" ? "default" : "ghost"}
          className={`flex-1 ${selectedTab === "active" ? "bg-gradient-primary shadow-glow" : ""}`}
          onClick={() => setSelectedTab("active")}
        >
          Active Quests ({activeQuests.length})
        </Button>
        <Button
          variant={selectedTab === "available" ? "default" : "ghost"}
          className={`flex-1 ${selectedTab === "available" ? "bg-gradient-primary shadow-glow" : ""}`}
          onClick={() => setSelectedTab("available")}
        >
          Available Quests ({availableQuests.length})
        </Button>
      </div>

      {/* Quest List */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {questsToShow.map((quest) => (
          <Card key={quest.id} className="bg-gradient-card border-primary/20 shadow-card hover:shadow-glow transition-all duration-300 group">
            <CardHeader>
              <div className="flex items-start justify-between">
                <div className="space-y-2">
                  <div className="flex items-center gap-2">
                    <CardTitle className="text-lg">{quest.title}</CardTitle>
                    {quest.aiGenerated && (
                      <Sparkles className="h-4 w-4 text-accent animate-pulse" />
                    )}
                  </div>
                  <div className="flex flex-wrap gap-2">
                    <Badge className={getDifficultyColor(quest.difficulty)}>
                      {quest.difficulty}
                    </Badge>
                    <Badge className={getQuestTypeColor(quest.questType)}>
                      {quest.questType}
                    </Badge>
                  </div>
                </div>
                <Trophy className="h-5 w-5 text-xp-primary" />
              </div>
              <CardDescription className="text-sm">
                {quest.description}
              </CardDescription>
            </CardHeader>
            
            <CardContent className="space-y-4">
              {/* Quest Progress (for active quests) */}
              {quest.status === "active" && quest.progress !== undefined && (
                <div className="space-y-2">
                  <div className="flex justify-between text-sm">
                    <span>Progress</span>
                    <span className="text-primary font-medium">{quest.progress}%</span>
                  </div>
                  <Progress 
                    value={quest.progress} 
                    className="h-2 bg-muted"
                  />
                </div>
              )}

              {/* Quest Info */}
              <div className="grid grid-cols-3 gap-4 text-sm">
                <div className="flex items-center gap-1">
                  <Clock className="h-3 w-3 text-muted-foreground" />
                  <span>{quest.duration}</span>
                </div>
                <div className="flex items-center gap-1">
                  <Users className="h-3 w-3 text-muted-foreground" />
                  <span>{quest.currentPlayers}/{quest.maxPlayers}</span>
                </div>
                <div className="flex items-center gap-1">
                  <Zap className="h-3 w-3 text-xp-primary" />
                  <span className="text-xp-primary font-medium">{quest.rewards.xp} XP</span>
                </div>
              </div>

              {/* Rewards Preview */}
              {(quest.rewards.badges || quest.rewards.items) && (
                <div className="space-y-2">
                  <p className="text-sm font-medium">Rewards:</p>
                  <div className="flex flex-wrap gap-1">
                    {quest.rewards.badges?.map((badge) => (
                      <Badge key={badge} variant="outline" className="text-xs">
                        {badge}
                      </Badge>
                    ))}
                    {quest.rewards.items?.map((item) => (
                      <Badge key={item} variant="outline" className="text-xs bg-accent/10 text-accent">
                        {item}
                      </Badge>
                    ))}
                  </div>
                </div>
              )}

              {/* Action Button */}
              <Button 
                className="w-full transition-all duration-300 group-hover:shadow-glow"
                variant={quest.status === "active" ? "outline" : "default"}
              >
                {quest.status === "active" ? (
                  <>Continue Quest</>
                ) : (
                  <>
                    <Play className="h-4 w-4 mr-2" />
                    Start Adventure
                  </>
                )}
              </Button>
            </CardContent>
          </Card>
        ))}
      </div>

      {/* Generate New Quest CTA */}
      <Card className="bg-gradient-primary border-primary/20 shadow-glow">
        <CardContent className="p-6 text-center">
          <Sparkles className="h-8 w-8 mx-auto mb-3 animate-float" />
          <h3 className="text-lg font-bold mb-2">Want a Personal Challenge?</h3>
          <p className="text-primary-foreground/80 mb-4">
            Our AI can generate a unique quest based on your interests, current location, and campus events
          </p>
          <Button variant="secondary" className="bg-primary-foreground text-primary hover:bg-primary-foreground/90">
            Generate AI Quest
          </Button>
        </CardContent>
      </Card>
    </div>
  );
};

export default QuestSystem;